import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";
import ClientOnly from "./components/ClientOnly";
import RegisterModal from "./components/Models/RegisterModal";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AirBnb",
  description: "Generated by create next app",
};

const fonts = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        <ClientOnly>
          <RegisterModal />
          <NavBar />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
